name:                day5
version:             0.1.0.0
github:              "erochest/day5"
license:             BSD3
author:              "Eric Rochester"
maintainer:          "erochest@gmail.com"
copyright:           "Eric Rochester"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Play

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/erochest/day5#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  day5-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent
    - bytestring
    - unordered-containers
