name:                day2
version:             0.1.0.0
github:              "erochest/day2"
license:             BSD3
author:              "Eric Rochester"
maintainer:          "erochest@gmail.com"
copyright:           "Eric Rochester"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Play

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/erochest/day2#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  day2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytestring
    - unordered-containers
    - hashable
    # - day2

# tests:
#   day2-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - day2
